### ISSUE TITLE
Can't find the right dependencies

### ISSUE THREAD

**Issue by Antt85** [aleksandr-m/struts2-pdfstream#1]
Hi, can you please tell me what version of which .jar should i use. I tried many, iText etc but i always have some classNotFound or methodNotFound exception.
Thanks !

**Comment by aleksandr-m** [comment]
Add this jars to your project classpath:

struts2-pdfstream-plugin-1.3.0.jar
flying-saucer-core-9.0.7.jar
flying-saucer-pdf-9.0.7.jar
itext-2.1.7.jar
jsoup-1.8.1.jar

**Comment by Antt85** [comment]
Thanks for the answer.

Is there a way to convert jsp to pdf but without proposing it to download
for the user and instead saving it directly on the server ? What i'm trying
to do is to offer a service where the user can download an archive with
multiple pdf ( created from the jsp).

Also the pdf I create from the jsp is not complete, maybe because of the margin because the right part of my JSP doesn't appear.

2015-04-15 20:09 GMT+02:00 Aleksandr Mashchenko notifications@github.com:

**Comment by aleksandr-m** [comment]
This isn't a job of S2 result, hence it is out of scope of this plugin.

_the right part of my JSP doesn't appear_ - yes you need to fit content into pdf, additionally you can switch pdf to landscape layout via css.
