### ISSUE TITLE
values written in the text fields are not saved in PDF.

### ISSUE THREAD

**Issue by ranjan1423** [aleksandr-m/struts2-pdfstream#2]
Hi,
I am trying to save the PDF with the values written in the text fields. it is creating textfields only not containing any value.

**Comment by aleksandr-m** [comment]
Only the initial values set in `value` attribute will be in pdf.

**Comment by ranjan1423** [comment]
So, if we have a form filled by user and we want to save the data with the text in text boxes / text area  and checkboxes to PDF file...... is it possible?

**Comment by aleksandr-m** [comment]
After user filled in form and submitted it, show them page with the values they've provided and from this view generate pdf (you can use js to auto redirect to pdf generation action). You can use input fields with `value` attribute set for this view, if you want to. But simple div-s / table-s will look better in pdf.
