### ISSUE TITLE
list of check boxes with iterator not working properly.

### ISSUE THREAD

**Issue by ranjan1423** [aleksandr-m/struts2-pdfstream#3]
Hi,
I got list from database and generated checkboxes with iterator. it is showing properly on JSP, but it is not comming properly on PDF.

**Comment by aleksandr-m** [comment]
Show your iterator. You need to set `checked` attribute.

**Comment by ranjan1423** [comment]
HI aleksandr-m,

actually i am getting 7 records from database, on JSP page 7 checkboxes are rendered with labels. but on PDF only one Checkbox is available, there is no any issue with labels. as per you suggestion I put checked attribute but still result is same.

here is the code.

`<s:iterator value="equipmentList" status="equipmtListStatus">
           <tr>
              <td><s:checkbox name="checkedList" fieldValue="%{equipment_name}" theme="simple" checked="checked"></s:checkbox></td>
              <td><s:property value="equipment_name" /></td>
              <td><s:property value="equipment_price" /></td>
              <td><s:property value="quantity" /></td>
              <td><s:property value="eq_description" /></td>
              <td><s:property value="total" /></td>
           </tr>
           </s:iterator>`

**Comment by ranjan1423** [comment]
:) 

HI aleksandr-m,
we got the solution. we have to provide unique name to the checkboxes like this. 

`name="%{equipment_name}"`

this is working fine.....

thanks for giving time.
hence i am closing this issue.
