### ISSUE TITLE
Support for Asian languages

### ISSUE THREAD

**Issue by elfwine** [aleksandr-m/struts2-pdfstream#4]
Thank you for this plugin.
However, it would be great if the Asian texts are supported, like Chinese/Japanese/Korean languages.
I guess it is only a matter of fonts, maybe the old iTextAsian.jar can be used.

Thanks.

**Comment by aleksandr-m** [comment]
You should be able to add fonts in CSS with the `@font-face` at-rule, like usually.

```
@font-face {
    font-family: 'your_font_family';
    src: url('your_font.ttf');
}
.some {
    font-family: 'your_font_family';
}
```

**Comment by elfwine** [comment]
Yeah, that's work. Thanks. ;)
